<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['name' => 'AED', 'symbol' => 'د.إ'],
            ['name' => 'AFN', 'symbol' => '؋'],
            ['name' => 'ALL', 'symbol' => 'Lek'],
            ['name' => 'AMD', 'symbol' => 'դր.'],
            ['name' => 'ANG', 'symbol' => 'ƒ'],
            ['name' => 'AOA', 'symbol' => 'Kz'],
            ['name' => 'ARS', 'symbol' => '$'],
            ['name' => 'AUD', 'symbol' => 'A$'],
            ['name' => 'AWG', 'symbol' => 'ƒ'],
            ['name' => 'AZN', 'symbol' => '₼'],
            ['name' => 'BAM', 'symbol' => 'KM'],
            ['name' => 'BBD', 'symbol' => '$'],
            ['name' => 'BDT', 'symbol' => '৳'],
            ['name' => 'BGN', 'symbol' => 'лв'],
            ['name' => 'BHD', 'symbol' => 'ب.د'],
            ['name' => 'BIF', 'symbol' => 'FBu'],
            ['name' => 'BMD', 'symbol' => '$'],
            ['name' => 'BND', 'symbol' => 'B$'],
            ['name' => 'BOB', 'symbol' => 'Bs.'],
            ['name' => 'BRL', 'symbol' => 'R$'],
            ['name' => 'BSD', 'symbol' => '$'],
            ['name' => 'BTN', 'symbol' => 'Nu.'],
            ['name' => 'BWP', 'symbol' => 'P'],
            ['name' => 'BYN', 'symbol' => 'Br'],
            ['name' => 'BZD', 'symbol' => '$'],
            ['name' => 'CAD', 'symbol' => 'C$'],
            ['name' => 'CDF', 'symbol' => 'Fr'],
            ['name' => 'CHF', 'symbol' => 'CHF'],
            ['name' => 'CLP', 'symbol' => '$'],
            ['name' => 'CNY', 'symbol' => '¥'],
            ['name' => 'COP', 'symbol' => '$'],
            ['name' => 'CRC', 'symbol' => '₡'],
            ['name' => 'CUC', 'symbol' => '$'],
            ['name' => 'CUP', 'symbol' => '₱'],
            ['name' => 'CVE', 'symbol' => 'Esc'],
            ['name' => 'CZK', 'symbol' => 'Kč'],
            ['name' => 'DJF', 'symbol' => 'Fdj'],
            ['name' => 'DKK', 'symbol' => 'kr'],
            ['name' => 'DOP', 'symbol' => 'RD$'],
            ['name' => 'DZD', 'symbol' => 'دج'],
            ['name' => 'EGP', 'symbol' => 'ج.م'],
            ['name' => 'ERN', 'symbol' => 'Nfk'],
            ['name' => 'ETB', 'symbol' => 'ብር'],
            ['name' => 'EUR', 'symbol' => '€'],
            ['name' => 'FJD', 'symbol' => '$'],
            ['name' => 'FKP', 'symbol' => '£'],
            ['name' => 'GBP', 'symbol' => '£'],
            ['name' => 'GEL', 'symbol' => 'ლ'],
            ['name' => 'GHS', 'symbol' => '₵'],
            ['name' => 'GIP', 'symbol' => '£'],
            ['name' => 'GMD', 'symbol' => 'D'],
            ['name' => 'GNF', 'symbol' => 'FG'],
            ['name' => 'GTQ', 'symbol' => 'Q'],
            ['name' => 'GYD', 'symbol' => '$'],
            ['name' => 'HKD', 'symbol' => '$'],
            ['name' => 'HNL', 'symbol' => 'L'],
            ['name' => 'HRK', 'symbol' => 'kn'],
            ['name' => 'HTG', 'symbol' => 'G'],
            ['name' => 'HUF', 'symbol' => 'Ft'],
            ['name' => 'IDR', 'symbol' => 'Rp'],
            ['name' => 'ILS', 'symbol' => '₪'],
            ['name' => 'INR', 'symbol' => '₹'],
            ['name' => 'IQD', 'symbol' => 'د.ع'],
            ['name' => 'IRR', 'symbol' => '﷼'],
            ['name' => 'ISK', 'symbol' => 'kr'],
            ['name' => 'JMD', 'symbol' => '$'],
            ['name' => 'JOD', 'symbol' => 'د.ا'],
            ['name' => 'JPY', 'symbol' => '¥'],
            ['name' => 'KES', 'symbol' => 'KSh'],
            ['name' => 'KGS', 'symbol' => 'с'],
            ['name' => 'KHR', 'symbol' => '៛'],
            ['name' => 'KMF', 'symbol' => 'CF'],
            ['name' => 'KRW', 'symbol' => '₩'],
            ['name' => 'KWD', 'symbol' => 'د.ك'],
            ['name' => 'KYD', 'symbol' => '$'],
            ['name' => 'KZT', 'symbol' => '₸'],
            ['name' => 'LAK', 'symbol' => '₭'],
            ['name' => 'LBP', 'symbol' => 'ل.ل'],
            ['name' => 'LKR', 'symbol' => 'Rs'],
            ['name' => 'LRD', 'symbol' => '$'],
            ['name' => 'LSL', 'symbol' => 'M'],
            ['name' => 'LTL', 'symbol' => 'Lt'],
            ['name' => 'LVL', 'symbol' => 'Ls'],
            ['name' => 'LYD', 'symbol' => 'د.ل'],
            ['name' => 'MAD', 'symbol' => 'د.م'],
            ['name' => 'MDL', 'symbol' => 'lei'],
            ['name' => 'MGA', 'symbol' => 'Ar'],
            ['name' => 'MKD', 'symbol' => 'ден'],
            ['name' => 'MMK', 'symbol' => 'Ks'],
            ['name' => 'MNT', 'symbol' => '₮'],
            ['name' => 'MOP', 'symbol' => 'MOP$'],
            ['name' => 'MUR', 'symbol' => '₨'],
            ['name' => 'MVR', 'symbol' => 'Rf'],
            ['name' => 'MWK', 'symbol' => 'MK'],
            ['name' => 'MXN', 'symbol' => '$'],
            ['name' => 'MYR', 'symbol' => 'RM'],
            ['name' => 'MZN', 'symbol' => 'MT'],
            ['name' => 'NAD', 'symbol' => '$'],
            ['name' => 'NGN', 'symbol' => '₦'],
            ['name' => 'NIO', 'symbol' => 'C$'],
            ['name' => 'NKR', 'symbol' => '₣'],
            ['name' => 'NPR', 'symbol' => 'Rs'],
            ['name' => 'NZD', 'symbol' => 'NZ$'],
            ['name' => 'OMR', 'symbol' => 'ر.ع.'],
            ['name' => 'PAB', 'symbol' => 'B/.'],
            ['name' => 'PEN', 'symbol' => 'S/'],
            ['name' => 'PGK', 'symbol' => 'K'],
            ['name' => 'PHP', 'symbol' => '₱'],
            ['name' => 'PKR', 'symbol' => '₨'],
            ['name' => 'PLN', 'symbol' => 'zł'],
            ['name' => 'PYG', 'symbol' => 'Gs'],
            ['name' => 'QAR', 'symbol' => 'ر.ق'],
            ['name' => 'RON', 'symbol' => 'lei'],
            ['name' => 'RSD', 'symbol' => 'дин.'],
            ['name' => 'RUB', 'symbol' => '₽'],
            ['name' => 'RWF', 'symbol' => 'FRw'],
            ['name' => 'SAR', 'symbol' => 'ر.س'],
            ['name' => 'SBD', 'symbol' => '$'],
            ['name' => 'SCR', 'symbol' => '₨'],
            ['name' => 'SDG', 'symbol' => 'ج.س'],
            ['name' => 'SEK', 'symbol' => 'kr'],
            ['name' => 'SGD', 'symbol' => 'S$'],
            ['name' => 'SHP', 'symbol' => '£'],
            ['name' => 'SLL', 'symbol' => 'Le'],
            ['name' => 'SOS', 'symbol' => 'Sh'],
            ['name' => 'SRD', 'symbol' => '$'],
            ['name' => 'SSP', 'symbol' => '£'],
            ['name' => 'STN', 'symbol' => 'Db'],
            ['name' => 'SYP', 'symbol' => 'ل.س'],
            ['name' => 'SZL', 'symbol' => 'L'],
            ['name' => 'THB', 'symbol' => '฿'],
            ['name' => 'TJS', 'symbol' => 'SM'],
            ['name' => 'TMT', 'symbol' => 'm'],
            ['name' => 'TND', 'symbol' => 'د.ت'],
            ['name' => 'TOP', 'symbol' => 'T$'],
            ['name' => 'TRY', 'symbol' => '₺'],
            ['name' => 'TTD', 'symbol' => '$'],
            ['name' => 'TWD', 'symbol' => 'NT$'],
            ['name' => 'TZS', 'symbol' => 'Sh'],
            ['name' => 'UAH', 'symbol' => '₴'],
            ['name' => 'UGX', 'symbol' => 'Sh'],
            ['name' => 'USD', 'symbol' => '$'],
            ['name' => 'UYU', 'symbol' => '$'],
            ['name' => 'UZS', 'symbol' => 'лв'],
            ['name' => 'VEF', 'symbol' => 'Bs'],
            ['name' => 'VES', 'symbol' => 'Bs.S'],
            ['name' => 'VND', 'symbol' => '₫'],
            ['name' => 'VUV', 'symbol' => 'Vt'],
            ['name' => 'WST', 'symbol' => 'T'],
            ['name' => 'XAF', 'symbol' => 'FCFA'],
            ['name' => 'XCD', 'symbol' => '$'],
            ['name' => 'XOF', 'symbol' => 'CFA'],
            ['name' => 'XPF', 'symbol' => 'CFPF'],
            ['name' => 'YER', 'symbol' => 'ر.ي'],
            ['name' => 'ZAR', 'symbol' => 'R'],
            ['name' => 'ZMW', 'symbol' => 'K'],
        ];

        foreach ($currencies as $currency) {
            Currency::create([
                'name' => $currency['name'],
                'symbol' => $currency['symbol'],
            ]);
        }
    }
}
